---
title: "plot4"
author: "Bhumika Agrawal"
date: "5/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Importing the dataset
```{r}
powerconsumption <- read.table("D:/Coursera/EDA/Week 1/exdata_data_household_power_consumption/household_power_consumption.txt",header = TRUE, sep = ";",stringsAsFactors = FALSE)
powerData <- powerconsumption[powerconsumption$Date %in% c("1/2/2007","2/2/2007") ,]
head(powerData)
```

```{r}
datetime <- strptime(paste(powerData$Date, powerData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(datetime,powerData$Global_active_power,type = "l", xlab = "", ylab = "Global Active Power")
plot(datetime,powerData$Voltage,type = "l", ylab = "Voltage")
plot(datetime, powerData$Sub_metering_1,col = "black", type="l",xlab = "", ylab="Energy Sub Metering")
lines(datetime, powerData$Sub_metering_2,col = "red", type="l")
lines(datetime, powerData$Sub_metering_3,col = "blue", type="l")
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = 1, col = c("black", "red", "blue"))
plot(datetime,powerData$Global_reactive_power,type = "l", ylab = "Global Reactive Power")
dev.off()
```
