---
title: "Plot4"
author: "Bhumika Agrawal"
date: "5/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
NEI <- readRDS('summarySCC_PM25.rds')
SCC <- readRDS('Source_Classification_Code.rds')
```

```{r}
motorSources <- subset(SCC, grepl("Motor", SCC.Level.Three,ignore.case = TRUE))
dim(motorSources)
motorSCC <- unique(motorSources$SCC)
```


```{r}
motorData <- subset(NEI, SCC %in% motorSCC & (fips == "24510" | fips == "06037"))
dim(motorData)
library(ggplot2)
```

```{r}
png(file = "./plot6.png",width = 480, height = 480)
ggplot(motorData,aes(factor(year),Emissions)) + geom_bar(stat = "identity") + labs(x = "Year", y = "Emissions(in tons)", title = "Motor Vehicle Related Emissions") + facet_grid(.~fips)
dev.off()
```

The emissions for LA county is significantly higher than Baltimore. The change in emissions is also higher in LA. For Baltimore, emissions rise in the middle but drop again in 2008 so the overall change is less.Whereas in LA, the emissions rise steadily leading to greater change.

